# -*- ruby -*-
#--
# Copyright 2008 Danny Coates, Ashkan Farhadtouski
# All rights reserved.
# See LICENSE for permissions.
#++
#AUTOGENERATED Thing extension

module HealthVault
  module WCData
    module Thing
      class Thing        
        @@class_hash = Hash.new  
        
        @@class_hash['d3170d30-a41b-4bde-a116-87698c8a001a'] = HealthVault::WCData::Thing::Calorieguideline::Calorieguideline
        @@class_hash['796C186F-B874-471c-8468-3EEFF73BF66E'] = HealthVault::WCData::Thing::Cholesterolprofile::Cholesterolprofile
        @@class_hash['162dd12d-9859-4a66-b75f-96760d67072b'] = HealthVault::WCData::Thing::Contact::Contact
        @@class_hash['ca3c57f4-f4c1-4e15-be67-0a3caf5414ed'] = HealthVault::WCData::Thing::BloodPressure::Bloodpressure
        @@class_hash['92ba621e-66b3-4a01-bd73-74844aed4f5b'] = HealthVault::WCData::Thing::Personal::Personal
        @@class_hash['a5294488-f865-4ce3-92fa-187cd3b58930'] = HealthVault::WCData::Thing::Personalimage::Personalimage
        @@class_hash['b7925180-d69e-48fa-ae1d-cb3748ca170e'] = HealthVault::WCData::Thing::Weightgoal::Weightgoal
        @@class_hash['3d34d87e-7fc1-4153-800f-f56592cb0d17'] = HealthVault::WCData::Thing::Weight::Weight
        @@class_hash['adaf49ad-8e10-49f8-9783-174819e97051'] = HealthVault::WCData::Thing::Cardiacprofile::Cardiacprofile
        @@class_hash['464083cc-13de-4f3e-a189-da8e47d5651b'] = HealthVault::WCData::Thing::Encounter::Encounter
        @@class_hash['E4911BD3-61BF-4E10-AE78-9C574B888B8F'] = HealthVault::WCData::Thing::Radiologylabresults::Radiologylabresults
        @@class_hash['80CF4080-AD3F-4BB5-A0B5-907C22F73017'] = HealthVault::WCData::Thing::Diabeticprofile::Diabeticprofile
        @@class_hash['d4b48e6b-50fa-4ba8-ac73-7d64a68dc328'] = HealthVault::WCData::Thing::Link::Link
        @@class_hash['9ad2a94f-c6a4-4d78-8b50-75b65be0e250'] = HealthVault::WCData::Thing::Applicationdatareference::Applicationdatareference
        @@class_hash['40750a6a-89b2-455c-bd8d-b420a4cb500b'] = HealthVault::WCData::Thing::Height::Height
        @@class_hash['4B18AEB6-5F01-444C-8C70-DBF13A2F510B'] = HealthVault::WCData::Thing::Appointment::Appointment
        @@class_hash['52bf9104-2c5e-4f1f-a66d-552ebcc53df7'] = HealthVault::WCData::Thing::Allergy::Allergy
        @@class_hash['031F5706-7F1A-11DB-AD56-7BD355D89593'] = HealthVault::WCData::Thing::SleepJournalPM::Sleeppm
        @@class_hash['11C52484-7F1A-11DB-AEAC-87D355D89593'] = HealthVault::WCData::Thing::SleepJournalAM::Sleepam
        @@class_hash['3a54f95f-03d8-4f62-815f-f691fc94a500'] = HealthVault::WCData::Thing::Bloodoxygensaturation::Bloodoxygensaturation
        @@class_hash['6705549b-0e3d-474e-bfa7-8197ddd6786a'] = HealthVault::WCData::Thing::Familyhistorycondition::Familyhistorycondition
        @@class_hash['879e7c04-4e8a-4707-9ad3-b054df467ce4'] = HealthVault::WCData::Thing::BloodGlucose::Bloodglucose
        @@class_hash['3D4BDF01-1B3E-4AFC-B41C-BD3E641A6DA7'] = HealthVault::WCData::Thing::EncounterV1::Encounter
        @@class_hash['85a21ddb-db20-4c65-8d30-33c899ccf612'] = HealthVault::WCData::Thing::Exercise::Exercise
        @@class_hash['55d33791-58de-4cae-8c78-819e12ba5059'] = HealthVault::WCData::Thing::Questionanswer::Questionanswer
        @@class_hash['7b2ea78c-4b78-4f75-a6a7-5396fe38b09a'] = HealthVault::WCData::Thing::Aerobicprofile::Aerobicprofile
        @@class_hash['dd710b31-2b6f-45bd-9552-253562b9a7c1'] = HealthVault::WCData::Thing::Bodydimension::Bodydimension
        @@class_hash['B8FCB138-F8E6-436A-A15D-E3A2D6916094'] = HealthVault::WCData::Thing::MicrobiologyLabResults::Microbiologylabresults
        @@class_hash['90dbf000-fc55-4b92-b4a1-da45c36ad8bb'] = HealthVault::WCData::Thing::AerobicSession::Aerobicsession
        @@class_hash['9366440c-ec81-4b89-b231-308a4c4d70ed'] = HealthVault::WCData::Thing::Payer::Payer
        @@class_hash['c9287326-bb43-4194-858c-8b60768f000f'] = HealthVault::WCData::Thing::PasswordProtectedPackage::Protected::Package::Passwordprotectedpackage
        @@class_hash['167ecf6b-bb54-43f9-a473-507b334907e0'] = HealthVault::WCData::Thing::Medicationfill::Medicationfill
        @@class_hash['A9A76456-0357-493e-B840-598BBB9483FD'] = HealthVault::WCData::Thing::Dailymedicationusage::Dailymedicationusage
        @@class_hash['AEA2E8F2-11DD-4A7D-AB43-1D58764EBC19'] = HealthVault::WCData::Thing::Concern::Concern
        @@class_hash['5C5F1223-F63C-4464-870C-3E36BA471DEF'] = HealthVault::WCData::Thing::MedicationV1::Medication
        @@class_hash['cc23422c-4fba-4a23-b52a-c01d6cd53fdf'] = HealthVault::WCData::Thing::Familyhistoryperson::Familyhistoryperson
        @@class_hash['46d485cf-2b84-429d-9159-83152ba801f4'] = HealthVault::WCData::Thing::Pregnancy::Pregnancy
        @@class_hash['66ac44c7-1d60-4e95-bb5b-d21490e91057'] = HealthVault::WCData::Thing::Groupmembership::Groupmembership
        @@class_hash['22826e13-41e1-4ba3-8447-37dadd208fd8'] = HealthVault::WCData::Thing::Familyhistory::Familyhistory
        @@class_hash['5d8419af-90f0-4875-a370-0f881c18f6b3'] = HealthVault::WCData::Thing::Peakflow::Peakflow
        @@class_hash['822a5e5a-14f1-4d06-b92f-8f3f1b05218f'] = HealthVault::WCData::Thing::Directive::Directive
        @@class_hash['9c29c6b9-f40e-44ff-b24e-fba6f3074638'] = HealthVault::WCData::Thing::DietaryDailyIntake::Dietaryintakedaily
        @@class_hash['b81eb4a6-6eac-4292-ae93-3872d6870994'] = HealthVault::WCData::Thing::Heartrate::Heartrate
        @@class_hash['609319bf-35cc-40a4-b9d7-1b329679baaa'] = HealthVault::WCData::Thing::Lifegoal::Lifegoal
        @@class_hash['d65ad514-c492-4b59-bd05-f3f6cb43ceb3'] = HealthVault::WCData::Thing::Allergicepisode::Allergicepisode
        @@class_hash['58fd8ac4-6c47-41a3-94b2-478401f0e26c'] = HealthVault::WCData::Thing::Healthassessment::Healthassessment
        @@class_hash['7EA47715-CBA4-47F0-99D2-EB0A9FB4A85C'] = HealthVault::WCData::Thing::Healthcareproxy::Healthcareproxy
        @@class_hash['18adc276-5144-4e7e-bf6c-e56d8250adf8'] = HealthVault::WCData::Thing::Bodycomposition::Bodycomposition
        @@class_hash['e4501363-fb95-4a11-bb60-da64e98048b5'] = HealthVault::WCData::Thing::AerobicWeeklyGoal::Aerobicweekly
        @@class_hash['7ea7a1f9-880b-4bd4-b593-f5660f20eda8'] = HealthVault::WCData::Thing::Condition::Condition
        @@class_hash['921588d1-27bf-423c-8e55-650d2fedb3e0'] = HealthVault::WCData::Thing::Spirometer::Spirometer
        @@class_hash['e1f92d7f-9699-4483-8223-8442874ec6d9'] = HealthVault::WCData::Thing::Exercisesamples::Exercisesamples
        @@class_hash['bf516a61-5252-4c28-a979-27f45f62f78d'] = HealthVault::WCData::Thing::Basic::Basic
        @@class_hash['9d006053-116c-43cc-9554-e0cda43558cb'] = HealthVault::WCData::Thing::GeneticSnpResults::Geneticsnpresults
        @@class_hash['5800eab5-a8c2-482a-a4d6-f1db25ae08c3'] = HealthVault::WCData::Thing::Labtestresults::Labtestresults
        @@class_hash['bd0403c5-4ae2-4b0e-a8db-1888678e4528'] = HealthVault::WCData::Thing::File::File
        @@class_hash['3B3C053B-B1FE-4E11-9E22-D4B480DE74E8'] = HealthVault::WCData::Thing::InsulinInjection::Insulininjection
        @@class_hash['ff9ce191-2096-47d8-9300-5469a9883746'] = HealthVault::WCData::Thing::AsthmaInhaler::Asthmainhaler
        @@class_hash['6D39F894-F7AC-4FCE-AC78-B22693BF96E6'] = HealthVault::WCData::Thing::FamilyHistoryV1::Familyhistory
        @@class_hash['03efe378-976a-42f8-ae1e-507c497a8c6d'] = HealthVault::WCData::Thing::AsthmaInhalerUse::Asthmainhaleruse
        @@class_hash['e75fa095-31ed-4b30-b5f7-463963b5e734'] = HealthVault::WCData::Thing::Groupmembershipactivity::Groupmembershipactivity
        @@class_hash['EF9CF8D5-6C0B-4292-997F-4047240BC7BE'] = HealthVault::WCData::Thing::Device::Device
        @@class_hash['227F55FB-1001-4D4E-9F6A-8D893E07B451'] = HealthVault::WCData::Thing::HbA1C::HbA1C
        @@class_hash['cd3587b5-b6e1-4565-ab3b-1c3ad45eb04f'] = HealthVault::WCData::Thing::Immunization::Immunization
        @@class_hash['184166BE-8ADB-4D9C-8162-C403040E31AD'] = HealthVault::WCData::Thing::Insulininjectionuse::Diabetesinsulininjectionuse
        @@class_hash['F57746AF-9631-49DC-944E-2C92BEE0D1E9'] = HealthVault::WCData::Thing::Labtestresults::Labtestresults
        @@class_hash['02EF57A2-A620-425A-8E92-A301542CCA54'] = HealthVault::WCData::Thing::Dischargesummary::Dischargesummary
        @@class_hash['0A5F9A43-DC88-4E9F-890F-1F9159B76E7B'] = HealthVault::WCData::Thing::ProcedureV1::Procedure
        @@class_hash['df4db479-a1ba-42a2-8714-2b083b88150f'] = HealthVault::WCData::Thing::Procedure::Procedure
        @@class_hash['a5033c9d-08cf-4204-9bd3-cb412ce39fc0'] = HealthVault::WCData::Thing::ApplicationSpecific::Appspecific
        @@class_hash['4b7971d6-e427-427d-bf2c-2fbcf76606b3'] = HealthVault::WCData::Thing::Emotion::Emotion
        @@class_hash['7AB3E662-CC5B-4BE2-BF38-78F8AAD5B161'] = HealthVault::WCData::Thing::Annotation::Annotation
        @@class_hash['046d0ad7-6d7f-4bfd-afd4-4192ca2e913d'] = HealthVault::WCData::Thing::Contraindication::Contraindication
        @@class_hash['73822612-C15F-4B49-9E65-6AF369E55C65'] = HealthVault::WCData::Thing::Vitalsigns::Vitalsigns
        @@class_hash['5fd15cb7-b717-4b1c-89e0-1dbcf7f815dd'] = HealthVault::WCData::Thing::Respiratoryprofile::Respiratoryprofile
        @@class_hash['5E2C027E-3417-4CFC-BD10-5A6F2E91AD23'] = HealthVault::WCData::Thing::Problem::Problem
        @@class_hash['3d817dbe-af42-4a9d-a553-d1298b4d08fc'] = HealthVault::WCData::Thing::ImmunizationV1::Immunization
        @@class_hash['30cafccc-047d-4288-94ef-643571f7919d'] = HealthVault::WCData::Thing::Medication::Medication
        def self.guid_to_class(guid)
          return @@class_hash[guid]
        end        
      end
    end
  end
end
